# Generated by Django 3.1.1 on 2020-10-09 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0005_score_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='rank',
            field=models.IntegerField(default=0),
        ),
    ]
