# Generated by Django 3.1.1 on 2020-10-09 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0006_score_rank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='value',
        ),
        migrations.AddField(
            model_name='score',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
