# Generated by Django 3.1.1 on 2020-10-09 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0009_auto_20201009_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='players',
            field=models.ManyToManyField(null=True, related_name='games', to='info.Player'),
        ),
        migrations.AlterField(
            model_name='player',
            name='average_score',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='points_gained',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='total_score',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='total_wins',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='win_rate',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='rank',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='score',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
