# Generated by Django 3.1.1 on 2020-10-09 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0010_auto_20201009_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='players',
            field=models.ManyToManyField(blank=True, related_name='games', to='info.Player'),
        ),
        migrations.AlterField(
            model_name='player',
            name='average_score',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='player',
            name='points_gained',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='total_score',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='total_wins',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='win_rate',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='rank',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='score',
            name='score',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
