# Generated by Django 3.1.1 on 2020-10-09 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0012_auto_20201009_1848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='average_score',
        ),
        migrations.RemoveField(
            model_name='player',
            name='total_score',
        ),
        migrations.RemoveField(
            model_name='player',
            name='total_wins',
        ),
        migrations.RemoveField(
            model_name='player',
            name='win_rate',
        ),
    ]
