# Generated by Django 3.1.1 on 2020-10-16 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0013_auto_20201009_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='points_gained',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
