# Generated by Django 3.1.1 on 2020-11-18 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0014_auto_20201016_1838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='points_gained',
        ),
    ]
