# Generated by Django 3.1.1 on 2020-11-20 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0015_remove_player_points_gained'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
    ]
