# Generated by Django 3.1.1 on 2020-11-20 10:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0016_auto_20201120_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='place',
            field=models.CharField(default='塩光宅', max_length=30),
        ),
    ]
